/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetoindividual01;

import java.util.Random;

/**
 *
 * @author edual
 */
public class LeitorDeDados extends javax.swing.JFrame {

    /**
     * Creates new form LeitorDeDados
     */
    public LeitorDeDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pgbCPU = new javax.swing.JProgressBar();
        pgbDisco = new javax.swing.JProgressBar();
        pgbMemoria = new javax.swing.JProgressBar();
        lblMedia01 = new javax.swing.JLabel();
        lblMenor01 = new javax.swing.JLabel();
        lblMaior01 = new javax.swing.JLabel();
        lblMedia2 = new javax.swing.JLabel();
        lblMenor2 = new javax.swing.JLabel();
        lblMaior2 = new javax.swing.JLabel();
        lblMedia3 = new javax.swing.JLabel();
        lblMenor3 = new javax.swing.JLabel();
        lblMaior3 = new javax.swing.JLabel();
        btnLeitor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("CPU:");

        jLabel2.setText("Disco:");

        jLabel3.setText("Memoria:");

        lblMedia01.setText("Media de leiruras:");

        lblMenor01.setText("Menor leitura:");

        lblMaior01.setText("Maior Leitura:");

        lblMedia2.setText("Media de leiruras:");

        lblMenor2.setText("Menor leitura:");

        lblMaior2.setText("Maior Leitura:");

        lblMedia3.setText("Media de leiruras:");

        lblMenor3.setText("Menor leitura:");

        lblMaior3.setText("Maior Leitura:");

        btnLeitor.setText("Fazer uma leitura!");
        btnLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgbCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblMaior01)
                    .addComponent(lblMenor01)
                    .addComponent(lblMedia01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblMaior2)
                    .addComponent(lblMenor2)
                    .addComponent(lblMedia2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(pgbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaior3)
                    .addComponent(lblMenor3)
                    .addComponent(lblMedia3))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pgbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgbCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMedia01)
                        .addGap(30, 30, 30)
                        .addComponent(lblMenor01)
                        .addGap(32, 32, 32)
                        .addComponent(lblMaior01))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMedia2)
                        .addGap(30, 30, 30)
                        .addComponent(lblMenor2)
                        .addGap(32, 32, 32)
                        .addComponent(lblMaior2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMedia3)
                        .addGap(30, 30, 30)
                        .addComponent(lblMenor3)
                        .addGap(32, 32, 32)
                        .addComponent(lblMaior3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnLeitor)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Integer vezes = 0, mediaCPU, mediaDisco, mediaMemoria, leituraCPU = 0, leituraDisco = 0, leituraMemoria = 0;
    Integer maiorCPU = 0, menorCPU =101, maiorDisco = 0, menorDisco =101, maiorMemoria = 0, menorMemoria =101;

    private void btnLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeitorActionPerformed
        // TODO add your handling code here:
        Random aleatorio = new Random();
        vezes++;
        
        Integer porcetagemCPU = 0;
        Integer porcetagemDisco = 0;
        Integer porcetagemMemoria = 0;
        
        porcetagemCPU = aleatorio.nextInt(100)+1;
        porcetagemDisco = aleatorio.nextInt(100)+1;
        porcetagemMemoria = aleatorio.nextInt(100)+1;
        
        pgbCPU.setValue(porcetagemCPU);
        pgbDisco.setValue(porcetagemDisco);
        pgbMemoria.setValue(porcetagemMemoria);
        
        //Primeira rodada
        if (maiorCPU == 0 && maiorDisco == 0 && maiorMemoria == 0 && menorCPU ==101 && menorDisco ==101 && menorMemoria ==101){
            lblMaior01.setText("Maior leitura: " + porcetagemCPU + "%");
            lblMaior2.setText("Maior leitura: " + porcetagemDisco + "%");
            lblMaior3.setText("Maior leitura: " + porcetagemMemoria + "%");
            lblMenor01.setText("Menor leitura: " + porcetagemCPU + "%");
            lblMenor2.setText("Menor leitura: " + porcetagemDisco + "%");
            lblMenor3.setText("Menor leitura: " + porcetagemMemoria + "%");
        }
        
        
        //CPU
        leituraCPU = leituraCPU  + porcetagemCPU;
        mediaCPU = leituraCPU/vezes;
        
        lblMedia01.setText("Media de leituras: " + mediaCPU + "%");
        
        if (porcetagemCPU > maiorCPU){
            maiorCPU = porcetagemCPU;
            lblMaior01.setText("Maior leitura: " + maiorCPU + "%");
        }
        else if(porcetagemCPU < menorCPU){
            menorCPU = porcetagemCPU;
            lblMenor01.setText("Menor leitura: " + menorCPU + "%");
        }
        
        
        //Disco
        leituraDisco = leituraDisco  + porcetagemDisco;
        mediaDisco = leituraDisco/vezes;
        
        lblMedia2.setText("Media de leituras: " + mediaDisco + "%");
        
        if (porcetagemDisco > maiorDisco){
            maiorDisco = porcetagemDisco;
            lblMaior2.setText("Maior leitura: " + maiorDisco + "%");
        }
        else if(porcetagemDisco < menorDisco){
            menorDisco = porcetagemDisco;
            lblMenor2.setText("Menor leitura: " + menorDisco + "%");
        }
        
        
        //Memoria
        leituraMemoria = leituraMemoria  + porcetagemMemoria;
        mediaMemoria = leituraMemoria/vezes;
        
        lblMedia3.setText("Media de leituras: " + mediaMemoria + "%");
        
        if (porcetagemMemoria > maiorMemoria){
            maiorMemoria = porcetagemMemoria;
            lblMaior3.setText("Maior leitura: " + maiorMemoria + "%");
        }
        else if(porcetagemMemoria < menorMemoria){
            menorMemoria = porcetagemMemoria;
            lblMenor3.setText("Menor leitura: " + menorMemoria + "%");
        }
        
    }//GEN-LAST:event_btnLeitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeitorDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeitorDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeitorDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeitorDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeitorDeDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMaior01;
    private javax.swing.JLabel lblMaior2;
    private javax.swing.JLabel lblMaior3;
    private javax.swing.JLabel lblMedia01;
    private javax.swing.JLabel lblMedia2;
    private javax.swing.JLabel lblMedia3;
    private javax.swing.JLabel lblMenor01;
    private javax.swing.JLabel lblMenor2;
    private javax.swing.JLabel lblMenor3;
    private javax.swing.JProgressBar pgbCPU;
    private javax.swing.JProgressBar pgbDisco;
    private javax.swing.JProgressBar pgbMemoria;
    // End of variables declaration//GEN-END:variables
}
